apiVersion: v1
kind: ConfigMap
metadata:
  name: msvc-usuarios
data:
  port: "8001"
  db_host: docker-mariadb-db:3306
  database: msvc_usuarios
#  username: mariadb
#  password: mariadb
  super_password: root-secret-development
  curso_url: msvc-cursos:8002
  msvc-usuarios.yaml:  |-
    config:
      texto: Configurando ambiente por defecto
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: msvc-cursos
data:
  port: "8002"
  db_host: docker-postgres-db:5432
  database: msvc_cursos
#  username: postgres
#  password: postgres
  usuario_url: "msvc-usuarios:8001"