apiVersion: v1
kind: ConfigMap
metadata:
  name: msvc-usuarios
data:
  lb_auth_issuer_uri: http://172.31.148.176:31296
  lb_usuarios_uri: http://172.31.148.176:31457
  port: "8001"
  db_host: docker-mariadb-db:3306
  database: msvc_usuarios
#  username: mariadb
#  password: mariadb
  super_password: root-secret-development
  curso_url: msvc-cursos:8002
  msvc-usuarios.yaml:  |-
    config:
      texto: Configurando ambiente por defecto
    ---
    spring:
      config:
        activate:
          on-profile: dev
    config:
      texto: Configurando ambiente de desarrollo
    ---
    spring:
      config:
        activate:
          on-profile: pro
    config:
      texto: Configurando ambiente de produccion
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: msvc-cursos
data:
  port: "8002"
  db_host: docker-postgres-db:5432
  database: msvc_cursos
#  username: postgres
#  password: postgres
  usuario_url: "msvc-usuarios:8001"