apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-postgres-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-postgres-db
  template:
    metadata:
      labels:
        app: docker-postgres-db
    spec:
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: msvc-cursos
                  key: password
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: msvc-cursos
                  key: username
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: msvc-cursos
                  key: database
          volumeMounts:
            - name: data-postgres
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data-postgres
          persistentVolumeClaim:
            claimName: postgres-pvc