version: "3.9"
services:
  docker-mariadb-db:
    container_name: docker-mariadb-db
    image: mariadb:jammy
    ports:
      - "3306:3306"
    environment:
      MARIADB_USER: mariadb
      MARIADB_PASSWORD: mariadb
      MARIADB_ROOT_PASSWORD: root-secret-development
      MARIADB_DATABASE: msvc_usuarios
    volumes:
      - data-mysql:/var/lib/mysql
    restart: always
    networks:
      - spring

  msvc-usuarios:
    container_name: msvc-usuarios
    image: katamus/usuarios
#    build:
#      context: ./
#      dockerfile: ./msvc-usuarios/Dockerfile
    ports:
      - "8001:8001"
    environment:
      PORT: 8001
      DB_HOST: docker-mariadb-db:3306
      DB_DATABASE: msvc_usuarios
      DB_USERNAME: mariadb
      DB_PASSWORD: mariadb
      CURSOS_URL: ec2-34-203-207-171.compute-1.amazonaws.com:8002
    networks:
      - spring
    depends_on:
      - docker-mariadb-db
    restart: always

volumes:
  data-mysql:
    name: data-mysql

networks:
  spring:
    name: spring
    external: true


