version: "3.9"
services:
  docker-mariadb-db:
    image: mariadb:jammy
    ports:
      - "3306:3306"
    environment:
      MARIADB_USER: mariadb
      MARIADB_PASSWORD: mariadb
      MARIADB_ROOT_PASSWORD: root-secret-development
      MARIADB_DATABASE: msvc_usuarios
    volumes:
      - volume data-mysql:/var/lib/mysql
    restart: always
    networks:
      - spring

  docker-postgres-db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=msvc_cursos
    volumes:
      - data-postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - spring

  msvc-usuarios:



  msvc-cursos:

volumes:
  data-mysql:
  data-postgres:

networks:
  spring:


