apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  storageClassName: ""
#  storageClassName: standard
  accessModes:
    - ReadWriteMany
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-04c5ae42a9f856279
#    - ReadWriteOnce
#  hostPath:
#    path: /var/lib/mysql
#    type: DirectoryOrCreate